//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Placeholder.
        /// </summary>
        public static string AccomCard_ImagePlaceholder {
            get {
                return ResourceManager.GetString("AccomCard_ImagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Guests:.
        /// </summary>
        public static string AccomCard_MaxGuests {
            get {
                return ResourceManager.GetString("AccomCard_MaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Days:.
        /// </summary>
        public static string AccomCard_MinDays {
            get {
                return ResourceManager.GetString("AccomCard_MinDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string AccomCard_Reserve {
            get {
                return ResourceManager.GetString("AccomCard_Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string AccomCard_ViewDetails {
            get {
                return ResourceManager.GetString("AccomCard_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string AccomLookup_FilterCity {
            get {
                return ResourceManager.GetString("AccomLookup_FilterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string AccomLookup_FilterCountry {
            get {
                return ResourceManager.GetString("AccomLookup_FilterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days:.
        /// </summary>
        public static string AccomLookup_FilterDays {
            get {
                return ResourceManager.GetString("AccomLookup_FilterDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests:.
        /// </summary>
        public static string AccomLookup_FilterGuests {
            get {
                return ResourceManager.GetString("AccomLookup_FilterGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AccomLookup_FilterName {
            get {
                return ResourceManager.GetString("AccomLookup_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        public static string AccomLookup_FiltersHeader {
            get {
                return ResourceManager.GetString("AccomLookup_FiltersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string AccomLookup_FilterType {
            get {
                return ResourceManager.GetString("AccomLookup_FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AccomLookup_FilterTypeAll {
            get {
                return ResourceManager.GetString("AccomLookup_FilterTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Accommodations.
        /// </summary>
        public static string AccomLookup_Title {
            get {
                return ResourceManager.GetString("AccomLookup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d..
        /// </summary>
        public static string AccomReservation_DaysSuffix {
            get {
                return ResourceManager.GetString("AccomReservation_DaysSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string AccomReservation_Duration {
            get {
                return ResourceManager.GetString("AccomReservation_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string AccomReservation_EndDate {
            get {
                return ResourceManager.GetString("AccomReservation_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Information.
        /// </summary>
        public static string AccomReservation_GuestInfo {
            get {
                return ResourceManager.GetString("AccomReservation_GuestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve:.
        /// </summary>
        public static string AccomReservation_Header {
            get {
                return ResourceManager.GetString("AccomReservation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        public static string AccomReservation_NumGuests {
            get {
                return ResourceManager.GetString("AccomReservation_NumGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Stay Period.
        /// </summary>
        public static string AccomReservation_SelectPeriod {
            get {
                return ResourceManager.GetString("AccomReservation_SelectPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        public static string AccomReservation_StartDate {
            get {
                return ResourceManager.GetString("AccomReservation_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Accommodation.
        /// </summary>
        public static string AccomReservation_Title {
            get {
                return ResourceManager.GetString("AccomReservation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness Rating:.
        /// </summary>
        public static string AccomReview_Cleanliness {
            get {
                return ResourceManager.GetString("AccomReview_Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string AccomReview_Comment {
            get {
                return ResourceManager.GetString("AccomReview_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your stay at.
        /// </summary>
        public static string AccomReview_Header {
            get {
                return ResourceManager.GetString("AccomReview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images:.
        /// </summary>
        public static string AccomReview_Images {
            get {
                return ResourceManager.GetString("AccomReview_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Correctness Rating: .
        /// </summary>
        public static string AccomReview_OwnerCorrectness {
            get {
                return ResourceManager.GetString("AccomReview_OwnerCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string AccomReview_Submit {
            get {
                return ResourceManager.GetString("AccomReview_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string AccomReview_UploadImages {
            get {
                return ResourceManager.GetString("AccomReview_UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Review.
        /// </summary>
        public static string AccomReview_WindowTitle {
            get {
                return ResourceManager.GetString("AccomReview_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APARTMENT.
        /// </summary>
        public static string AccomType_Apartment {
            get {
                return ResourceManager.GetString("AccomType_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTTAGE.
        /// </summary>
        public static string AccomType_Cottage {
            get {
                return ResourceManager.GetString("AccomType_Cottage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOUSE.
        /// </summary>
        public static string AccomType_House {
            get {
                return ResourceManager.GetString("AccomType_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available: .
        /// </summary>
        public static string Anywhere_CardAvailable {
            get {
                return ResourceManager.GetString("Anywhere_CardAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days:.
        /// </summary>
        public static string Anywhere_CardDays {
            get {
                return ResourceManager.GetString("Anywhere_CardDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests:.
        /// </summary>
        public static string Anywhere_CardGuests {
            get {
                return ResourceManager.GetString("Anywhere_CardGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve This Offer.
        /// </summary>
        public static string Anywhere_CardReserveOffer {
            get {
                return ResourceManager.GetString("Anywhere_CardReserveOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of stay (days):.
        /// </summary>
        public static string Anywhere_FilterDuration {
            get {
                return ResourceManager.GetString("Anywhere_FilterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of period (optional): .
        /// </summary>
        public static string Anywhere_FilterEndDate {
            get {
                return ResourceManager.GetString("Anywhere_FilterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        public static string Anywhere_FilterNumGuests {
            get {
                return ResourceManager.GetString("Anywhere_FilterNumGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of period (optional): .
        /// </summary>
        public static string Anywhere_FilterStartDate {
            get {
                return ResourceManager.GetString("Anywhere_FilterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your perfect getaway.
        /// </summary>
        public static string Anywhere_Subtitle {
            get {
                return ResourceManager.GetString("Anywhere_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Anywhere, Anytime.
        /// </summary>
        public static string Anywhere_Title {
            get {
                return ResourceManager.GetString("Anywhere_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Forum.
        /// </summary>
        public static string CreateForum_CreateButton {
            get {
                return ResourceManager.GetString("CreateForum_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first comment or question: .
        /// </summary>
        public static string CreateForum_FirstComment {
            get {
                return ResourceManager.GetString("CreateForum_FirstComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Title:.
        /// </summary>
        public static string CreateForum_ForumTitle {
            get {
                return ResourceManager.GetString("CreateForum_ForumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Forum.
        /// </summary>
        public static string CreateForum_Header {
            get {
                return ResourceManager.GetString("CreateForum_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location (e.g., Belgrade, Serbia):.
        /// </summary>
        public static string CreateForum_Location {
            get {
                return ResourceManager.GetString("CreateForum_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a New Forum.
        /// </summary>
        public static string CreateForum_WindowTitle {
            get {
                return ResourceManager.GetString("CreateForum_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string ForumList_CommentsSuffix {
            get {
                return ResourceManager.GetString("ForumList_CommentsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a New Forum.
        /// </summary>
        public static string ForumList_CreateNew {
            get {
                return ResourceManager.GetString("ForumList_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ForumList_TagClosed {
            get {
                return ResourceManager.GetString("ForumList_TagClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Useful.
        /// </summary>
        public static string ForumList_TagUseful {
            get {
                return ResourceManager.GetString("ForumList_TagUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string ForumList_Title {
            get {
                return ResourceManager.GetString("ForumList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Forum.
        /// </summary>
        public static string ForumList_ViewForum {
            get {
                return ResourceManager.GetString("ForumList_ViewForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Forum.
        /// </summary>
        public static string ForumView_CloseForum {
            get {
                return ResourceManager.GetString("ForumView_CloseForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Comment.
        /// </summary>
        public static string ForumView_PostComment {
            get {
                return ResourceManager.GetString("ForumView_PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string ForumView_TagOwner {
            get {
                return ResourceManager.GetString("ForumView_TagOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited this location .
        /// </summary>
        public static string ForumView_TagVisited {
            get {
                return ResourceManager.GetString("ForumView_TagVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness Rating:.
        /// </summary>
        public static string GuestReview_Cleanliness {
            get {
                return ResourceManager.GetString("GuestReview_Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Review of Your Stay .
        /// </summary>
        public static string GuestReview_Header {
            get {
                return ResourceManager.GetString("GuestReview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Comment:.
        /// </summary>
        public static string GuestReview_OwnerComment {
            get {
                return ResourceManager.GetString("GuestReview_OwnerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Respecting Rating:.
        /// </summary>
        public static string GuestReview_RuleRespect {
            get {
                return ResourceManager.GetString("GuestReview_RuleRespect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review from Owner.
        /// </summary>
        public static string GuestReview_WindowTitle {
            get {
                return ResourceManager.GetString("GuestReview_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingApp - Welcome Guest.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere / Anytime.
        /// </summary>
        public static string Menu_AnywhereAnytime {
            get {
                return ResourceManager.GetString("Menu_AnywhereAnytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string Menu_Forums {
            get {
                return ResourceManager.GetString("Menu_Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reservations.
        /// </summary>
        public static string Menu_MyReservations {
            get {
                return ResourceManager.GetString("Menu_MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Accommodations.
        /// </summary>
        public static string Menu_SearchAccommodations {
            get {
                return ResourceManager.GetString("Menu_SearchAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reservation.
        /// </summary>
        public static string MyReservations_Cancel {
            get {
                return ResourceManager.GetString("MyReservations_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests: .
        /// </summary>
        public static string MyReservations_Guests {
            get {
                return ResourceManager.GetString("MyReservations_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string MyReservations_Rate {
            get {
                return ResourceManager.GetString("MyReservations_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string MyReservations_ReportEnd {
            get {
                return ResourceManager.GetString("MyReservations_ReportEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF Report.
        /// </summary>
        public static string MyReservations_ReportGenerate {
            get {
                return ResourceManager.GetString("MyReservations_ReportGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Reservation Report.
        /// </summary>
        public static string MyReservations_ReportSection {
            get {
                return ResourceManager.GetString("MyReservations_ReportSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        public static string MyReservations_ReportStart {
            get {
                return ResourceManager.GetString("MyReservations_ReportStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string MyReservations_Reschedule {
            get {
                return ResourceManager.GetString("MyReservations_Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Request:.
        /// </summary>
        public static string MyReservations_RescheduleRequest {
            get {
                return ResourceManager.GetString("MyReservations_RescheduleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reservations.
        /// </summary>
        public static string MyReservations_Title {
            get {
                return ResourceManager.GetString("MyReservations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MyReservations_ViewReview {
            get {
                return ResourceManager.GetString("MyReservations_ViewReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation:.
        /// </summary>
        public static string Reschedule_Accommodation {
            get {
                return ResourceManager.GetString("Reschedule_Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Reservation.
        /// </summary>
        public static string Reschedule_Current {
            get {
                return ResourceManager.GetString("Reschedule_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to Reschedule Reservation.
        /// </summary>
        public static string Reschedule_Header {
            get {
                return ResourceManager.GetString("Reschedule_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New End Date:.
        /// </summary>
        public static string Reschedule_NewEnd {
            get {
                return ResourceManager.GetString("Reschedule_NewEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Start Date:.
        /// </summary>
        public static string Reschedule_NewStart {
            get {
                return ResourceManager.GetString("Reschedule_NewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        public static string Reschedule_Period {
            get {
                return ResourceManager.GetString("Reschedule_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select New Dates.
        /// </summary>
        public static string Reschedule_SelectNew {
            get {
                return ResourceManager.GetString("Reschedule_SelectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string Reschedule_Send {
            get {
                return ResourceManager.GetString("Reschedule_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Reservation Change.
        /// </summary>
        public static string Reschedule_WindowTitle {
            get {
                return ResourceManager.GetString("Reschedule_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string Settings_DarkTheme {
            get {
                return ResourceManager.GetString("Settings_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_English {
            get {
                return ResourceManager.GetString("Settings_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language..
        /// </summary>
        public static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string Settings_LightTheme {
            get {
                return ResourceManager.GetString("Settings_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian (Latin).
        /// </summary>
        public static string Settings_Serbian {
            get {
                return ResourceManager.GetString("Settings_Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred application theme..
        /// </summary>
        public static string Settings_ThemeDescription {
            get {
                return ResourceManager.GetString("Settings_ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dates you selected are already booked. Here are some available alternatives for the same duration:.
        /// </summary>
        public static string SuggestedDates_Description {
            get {
                return ResourceManager.GetString("SuggestedDates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Unavailable.
        /// </summary>
        public static string SuggestedDates_Header {
            get {
                return ResourceManager.GetString("SuggestedDates_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Selected Date.
        /// </summary>
        public static string SuggestedDates_ReserveButton {
            get {
                return ResourceManager.GetString("SuggestedDates_ReserveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Dates.
        /// </summary>
        public static string SuggestedDates_WindowTitle {
            get {
                return ResourceManager.GetString("SuggestedDates_WindowTitle", resourceCulture);
            }
        }
    }
}
