using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BookingApp.Domain.Interfaces.ServiceInterfaces;
using BookingApp.Services.DTO;
using BookingApp.Domain.Interfaces;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace BookingApp.Services
{
        public class PDFAccommodationReportService : IPDFReportService
        {
            private readonly IAccommodationReviewService _accommodationReviewService;
            private readonly IAccommodationService _accommodationService;

            public PDFAccommodationReportService(IAccommodationReviewService accommodationReviewService, IAccommodationService accommodationService)
            {
                _accommodationReviewService = accommodationReviewService;
                _accommodationService = accommodationService;
            }

            public string GenerateAccommodationRatingsReport(List<AccommodationRatingDTO> ratings, DateTime fromDate, DateTime toDate, string ownerName)
            {
                string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), $"AccommodationRatingsReport_{DateTime.Now:yyyyMMdd_HHmmss}.pdf");
                Document document = new Document(PageSize.A4);

                try
                {
                    string fontPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts), "arial.ttf");
                    BaseFont bf;

                    if (File.Exists(fontPath))
                    {
                        bf = BaseFont.CreateFont(fontPath, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
                    }
                    else
                    {
                        bf = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1250, BaseFont.NOT_EMBEDDED);
                    }

                    Font titleFont = new Font(bf, 18, Font.BOLD, BaseColor.BLACK);
                    Font headerFont = new Font(bf, 12, Font.BOLD, BaseColor.BLACK);
                    Font normalFont = new Font(bf, 10, Font.NORMAL, BaseColor.BLACK);
                    Font subHeaderFont = new Font(bf, 10, Font.BOLD, BaseColor.BLACK);

                    PdfWriter.GetInstance(document, new FileStream(filePath, FileMode.Create));
                    document.Open();

                    document.Add(new Paragraph("Accommodation Ratings Report", titleFont) { Alignment = Element.ALIGN_CENTER, SpacingAfter = 15 });
                    document.Add(new Paragraph($"Report generated by: {ownerName}", subHeaderFont));
                    document.Add(new Paragraph($"Date: {DateTime.Now:dd.MM.yyyy}", subHeaderFont));
                    document.Add(new Paragraph($"Period: from {fromDate:dd.MM.yyyy} to {toDate:dd.MM.yyyy}", subHeaderFont));
                    document.Add(new Paragraph("\n"));

                    if (!ratings.Any())
                    {
                        document.Add(new Paragraph("No accommodation reviews found for the selected period.", normalFont));
                        document.Close();
                        return filePath; 
                    }

                    PdfPTable table = new PdfPTable(5)
                    {
                        WidthPercentage = 100,
                        SpacingBefore = 10
                    };
                    float[] widths = new float[] { 2.5f, 2.5f, 1.5f, 1.5f, 1.5f };
                    table.SetWidths(widths);

                    table.AddCell(new PdfPCell(new Phrase("Accommodation", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                    table.AddCell(new PdfPCell(new Phrase("Location", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                    table.AddCell(new PdfPCell(new Phrase("Cleanliness", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                    table.AddCell(new PdfPCell(new Phrase("Owner Rating", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                    table.AddCell(new PdfPCell(new Phrase("No. of Reviews", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });

                    foreach (var rating in ratings)
                    {
                        table.AddCell(new PdfPCell(new Phrase(rating.AccommodationName, normalFont)) { Padding = 5 });
                        table.AddCell(new PdfPCell(new Phrase(rating.Location, normalFont)) { Padding = 5 });
                        table.AddCell(new PdfPCell(new Phrase(rating.AverageCleanlinessRating.ToString("F2"), normalFont)) { Padding = 5, HorizontalAlignment = Element.ALIGN_CENTER });
                        table.AddCell(new PdfPCell(new Phrase(rating.AverageOwnerRating.ToString("F2"), normalFont)) { Padding = 5, HorizontalAlignment = Element.ALIGN_CENTER });
                        table.AddCell(new PdfPCell(new Phrase(rating.NumberOfReviews.ToString(), normalFont)) { Padding = 5, HorizontalAlignment = Element.ALIGN_CENTER });
                    }

                    document.Add(table);
                }
                catch (Exception ex)
                {
                    // Throw an exception to notify the calling layer (e.g., UI) about the error
                    throw new InvalidOperationException("An error occurred during PDF generation. Please check file permissions or font availability.", ex);
                }
                finally
                {
                    if (document.IsOpen())
                    {
                        document.Close();
                    }
                }

                return filePath;
            }
        }
}
