using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BookingApp.Domain.Interfaces.ServiceInterfaces;
using BookingApp.Services.DTO;
using BookingApp.Domain.Interfaces;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace BookingApp.Services
{
        public class PDFAccommodationReportService : IPDFReportService
        {
            private readonly IAccommodationReviewService _accommodationReviewService;
            private readonly IAccommodationService _accommodationService;
            private readonly IAccommodationRatingReportGenerator _reportGenerator;
        public PDFAccommodationReportService(IAccommodationReviewService accommodationReviewService, IAccommodationService accommodationService, IAccommodationRatingReportGenerator reportGenerator)
            {
                _accommodationReviewService = accommodationReviewService;
                _accommodationService = accommodationService;
            _reportGenerator = reportGenerator;

        }

        public string GenerateAccommodationRatingsReport(List<AccommodationRatingDTO> ratings, DateTime fromDate, DateTime toDate, string ownerName)
        {
            return _reportGenerator.Generate(ratings, fromDate, toDate, ownerName);
        }

        public class AccommodationRatingPdfGenerator : IAccommodationRatingReportGenerator
        {
            public string Generate(List<AccommodationRatingDTO> ratings, DateTime fromDate, DateTime toDate, string ownerName)
            {
                string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), $"AccommodationRatingsReport_{DateTime.Now:yyyyMMdd_HHmmss}.pdf");
                Document document = new Document(PageSize.A4);

                try
                {
                    var styles = GetReportStyles(); // MELOC manji od 10
                    PdfWriter.GetInstance(document, new FileStream(filePath, FileMode.Create));
                    document.Open();

                    AddReportHeader(document, fromDate, toDate, ownerName, styles); // MELOC manji od 10

                    if (!ratings.Any())
                    {
                        document.Add(new Paragraph("No accommodation reviews found for the selected period.", styles.NormalFont));
                    }
                    else
                    {
                        PdfPTable table = CreateRatingsTable(ratings, styles); // MELOC manji od 25
                        document.Add(table);
                    }
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("An error occurred during PDF generation.", ex);
                }
                finally
                {
                    if (document.IsOpen())
                    {
                        document.Close();
                    }
                }
                return filePath;
            }
            private class ReportStyles
            {
                public Font TitleFont { get; set; }
                public Font HeaderFont { get; set; }
                public Font NormalFont { get; set; }
                public Font SubHeaderFont { get; set; }
            }

            private ReportStyles GetReportStyles()
            {
                string fontPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts), "arial.ttf");
                BaseFont bf;

                if (File.Exists(fontPath))
                {
                    bf = BaseFont.CreateFont(fontPath, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
                }
                else
                {
                    bf = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1250, BaseFont.NOT_EMBEDDED);
                }

                return new ReportStyles
                {
                    TitleFont = new Font(bf, 18, Font.BOLD, BaseColor.BLACK),
                    HeaderFont = new Font(bf, 12, Font.BOLD, BaseColor.BLACK),
                    NormalFont = new Font(bf, 10, Font.NORMAL, BaseColor.BLACK),
                    SubHeaderFont = new Font(bf, 10, Font.BOLD, BaseColor.BLACK)
                };
            }

            private void AddReportHeader(Document document, DateTime fromDate, DateTime toDate, string ownerName, ReportStyles styles)
            {
                document.Add(new Paragraph("Accommodation Ratings Report", styles.TitleFont) { Alignment = Element.ALIGN_CENTER, SpacingAfter = 15 });
                document.Add(new Paragraph($"Report generated by: {ownerName}", styles.SubHeaderFont));
                document.Add(new Paragraph($"Date: {DateTime.Now:dd.MM.yyyy}", styles.SubHeaderFont));
                document.Add(new Paragraph($"Period: from {fromDate:dd.MM.yyyy} to {toDate:dd.MM.yyyy}", styles.SubHeaderFont));
                document.Add(new Paragraph("\n"));
            }
            private PdfPTable CreateRatingsTable(List<AccommodationRatingDTO> ratings, ReportStyles styles)
            {
                PdfPTable table = new PdfPTable(5)
                {
                    WidthPercentage = 100,
                    SpacingBefore = 10
                };
                float[] widths = new float[] { 2.5f, 2.5f, 1.5f, 1.5f, 1.5f };
                table.SetWidths(widths);

                AddTableHeader(table, styles.HeaderFont);

                foreach (var rating in ratings)
                {
                    AddDataRow(table, rating, styles.NormalFont);
                }
                return table;
            }
            private void AddTableHeader(PdfPTable table, Font headerFont)
            {
                table.AddCell(new PdfPCell(new Phrase("Accommodation", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                table.AddCell(new PdfPCell(new Phrase("Location", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                table.AddCell(new PdfPCell(new Phrase("Cleanliness", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                table.AddCell(new PdfPCell(new Phrase("Owner Rating", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
                table.AddCell(new PdfPCell(new Phrase("No. of Reviews", headerFont)) { HorizontalAlignment = Element.ALIGN_CENTER, Padding = 5, BackgroundColor = new BaseColor(240, 240, 240) });
            }
            private void AddDataRow(PdfPTable table, AccommodationRatingDTO rating, Font normalFont)
            {
                table.AddCell(new PdfPCell(new Phrase(rating.AccommodationName, normalFont)) { Padding = 5 });
                table.AddCell(new PdfPCell(new Phrase(rating.Location, normalFont)) { Padding = 5 });
                table.AddCell(new PdfPCell(new Phrase(rating.AverageCleanlinessRating.ToString("F2"), normalFont)) { Padding = 5, HorizontalAlignment = Element.ALIGN_CENTER });
                table.AddCell(new PdfPCell(new Phrase(rating.AverageOwnerRating.ToString("F2"), normalFont)) { Padding = 5, HorizontalAlignment = Element.ALIGN_CENTER });
                table.AddCell(new PdfPCell(new Phrase(rating.NumberOfReviews.ToString(), normalFont)) { Padding = 5, HorizontalAlignment = Element.ALIGN_CENTER });
            }
        }
    }
}
